install.packages("ggplot2")
install.packages("lubridate")
install.packages("Scale")
install.packages("reshape2")
install.packages("tm")
install.packages("SnowballC")
install.packages("RColorBrewer")
install.packages("wordcloud")
install.packages("stringr")
install.packages("syuzhet")
install.packages("dplyr")
text<- readLines("E:/chat5.txt")
docs<-Corpus(VectorSource(text))
trans<-content_transformer(function(x,pattern)gsub(pattern," ",x))
docs<-tm_map(docs,trans,"/")
docs<-tm_map(docs,trans,"@")
docs<-tm_map(docs,trans,"\\|")
docs<-tm_map(docs,content_transformer(tolower))
docs<-tm_map(docs,removeNumbers)
docs<-tm_map(docs,removeWords,stopwords("english"))
docs<-tm_map(docs,removePunctuation)
docs<-tm_map(docs,stripWhitespace)
docs<-tm_map(docs,stemDocument)
dtm<-TermDocumentMatrix(docs)
mat<-as.matrix(dtm)
v<-sort(rowSums(mat),decreasing = TRUE)
data<-data.frame(word = names(v),freq = v)
head(data,10)
set.seed(1056)
wordcloud(words = data$word, freq = data$freq, min.freq = 1, max.words = 500, random.order = FALSE, rot.per = 0.35, colors = brewer.pal(5,"Dark2"))
barplot(data[1:10,]$freq, las = 2, names.arg = data[1:10,]$word,col ="blue", main ="Most frequent words",ylab = "Word frequencies")
Sentiment<-get_nrc_sentiment(text)
head(Sentiment)
Sentiment <- get_nrc_sentiment(text)
text1 <- cbind(text,Sentiment)
TotalSentiment <- data.frame(colSums(text1[,c(2:11)]))
names(TotalSentiment) <- "count"
TotalSentiment <- cbind("sentiment" = rownames(TotalSentiment), TotalSentiment)
png(file = "E:/FinalAnalysis.png")
ggplot(data = TotalSentiment, aes(x = sentiment, y = count)) +geom_bar(aes(fill = sentiment), stat = "identity") + theme(legend.position = "none") +xlab("Sentiment") + ylab("Total Count") + ggtitle("Total Sentiment Score")
dev.off()
